### ISSUE TITLE
Please read

### ISSUE THREAD

**Issue by toi500** [amansoni7477030/OneYou_template#1]
Edit: Happy to help!

**Comment by amansoni7477030** [comment]
@toi500 Thank You

**Comment by toi500** [comment]
Any news with your app?

**Comment by amansoni7477030** [comment]
I did not get any reply yet

**Comment by toi500** [comment]
@amansoni7477030 Yesterday I told Henry about your PR and he told me he wasn't't aware of it. But now he is, so I expect he can review it soon. There is some PR in the main repo unresolved yet.

**Comment by amansoni7477030** [comment]
@toi500 is there any group where i can directly contact henry ? if i want to discuss things, this may be a great help!

**Comment by amansoni7477030** [comment]
> @amansoni7477030 Yesterday I told Henry about your PR and he told me he wasn't't aware of it. But now he is, so I expect he can review it soon. There is some PR in the main repo unresolved yet.

Thanks for the update🙂

**Comment by toi500** [comment]
> @toi500 is there any group where i can directly contact henry ? if i want to discuss things, this may be a great help!

Discord, man. Just send him a MD
https://discord.gg/jbaHfsRVBW

**Comment by amansoni7477030** [comment]
> > @toi500 is there any group where i can directly contact henry ? if i want to discuss things, this may be a great help!
> 
> Discord, man. Just send him a MD https://discord.gg/jbaHfsRVBW

Thanks 👍

**Comment by toi500** [comment]
@amansoni7477030 please tell me that this new autofocus option is only for non-mobiles devices?

**Comment by amansoni7477030** [comment]
> @amansoni7477030 please tell me that this new autofocus option is only for non-mobiles devices?

@toi500 This new feature is available for all types of devices. If it is set to true, it will work on all devices; if set to false, it will not work in any device.

**Comment by toi500** [comment]
> > @amansoni7477030 please tell me that this new autofocus option is only for non-mobiles devices?
> 
> @toi500 This new feature is available for all types of devices. If it is set to true, it will work on all devices; if set to false, it will not work in any device.

This cap the proposite of your PR

**Comment by amansoni7477030** [comment]
@toi500 what is your suggestion ?

**Comment by toi500** [comment]
> @toi500 what is your suggestion ?

@amansoni7477030 Check my comment on your PR, I added some videos.

**Comment by toi500** [comment]
My suggestion is what i say in your PR, my friend. Having the autoFocus feature on mobile by default is poinless, nobody needs it. Now with this change you need to choise for 1 inconveniece:

-Good on Mobile, bad on Desktop
-Bad on Mobile, good on Desktop

**Comment by amansoni7477030** [comment]
@toi500 the suggestion you mentioned has been applied by henry

**Comment by toi500** [comment]
> @toi500 the suggestion you mentioned has been applied by henry 

Thank you so much man for this PR, it was really needed.

Edit: If you come to discord, let me know. My nick is toi500

**Comment by amansoni7477030** [comment]
@toi500 You're Welcome! sent you friend request on discord check
